package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
)

// ServiceTemplate is a ready-made blocking recipe: one hook:<ID> toggles a
// forward drop rule over an FQDN address-list, scoped to the kids-devices
// src-address-list (kept in sync from kid-control by remote-hook.rsc).
// No dns/static entries: NXDOMAIN cannot be scoped by source (it would hit
// the whole LAN) and it poisons the router's own FQDN address-list
// resolution, draining the firewall layer.
type ServiceTemplate struct {
	ID      string   `json:"id"`    // param name / hook tag
	Title   string   `json:"title"` // param description
	Group   string   `json:"group"`
	Domains []string `json:"domains"`          // FQDNs: dns/static NXDOMAIN + address-list entries
	Ranges  []string `json:"ranges,omitempty"` // static CIDRs (game server networks etc.)
}

var templateCatalog = []ServiceTemplate{
	// --- video & streaming ---
	{ID: "youtube", Title: "YouTube", Group: "video",
		Domains: []string{"youtube.com", "youtu.be", "googlevideo.com", "ytimg.com", "youtube-nocookie.com"}},
	{ID: "tiktok", Title: "TikTok", Group: "video",
		Domains: []string{"tiktok.com", "tiktokcdn.com", "tiktokv.com", "ttlivecdn.com", "byteoversea.com", "musical.ly"}},
	{ID: "twitch", Title: "Twitch", Group: "video",
		Domains: []string{"twitch.tv", "ttvnw.net", "jtvnw.net", "twitchcdn.net"}},
	{ID: "netflix", Title: "Netflix", Group: "video",
		Domains: []string{"netflix.com", "nflxvideo.net", "nflximg.net", "nflxext.com"}},
	{ID: "kick", Title: "Kick", Group: "video",
		Domains: []string{"kick.com"}},
	// --- games ---
	{ID: "steam", Title: "Steam", Group: "games",
		Domains: []string{"steampowered.com", "steamcommunity.com", "steamcontent.com", "steamstatic.com", "steamusercontent.com"},
		Ranges:  []string{"155.133.224.0/19", "162.254.192.0/21", "146.66.152.0/21", "185.25.180.0/22"}}, // Valve AS32590
	{ID: "roblox", Title: "Roblox", Group: "games",
		Domains: []string{"roblox.com", "rbxcdn.com"},
		Ranges:  []string{"128.116.0.0/17"}}, // Roblox AS22697 game servers
	{ID: "minecraft", Title: "Minecraft", Group: "games",
		Domains: []string{"minecraft.net", "mojang.com", "minecraftservices.com"}},
	{ID: "fortnite", Title: "Fortnite / Epic", Group: "games",
		Domains: []string{"fortnite.com", "epicgames.com", "epicgames.dev", "unrealengine.com"}},
	// --- social ---
	{ID: "twitter", Title: "Twitter / X", Group: "social",
		Domains: []string{"twitter.com", "x.com", "twimg.com", "t.co"}},
	{ID: "facebook", Title: "Facebook", Group: "social",
		Domains: []string{"facebook.com", "fbcdn.net", "fb.com", "messenger.com"}},
	{ID: "instagram", Title: "Instagram", Group: "social",
		Domains: []string{"instagram.com", "cdninstagram.com", "ig.me"}},
	{ID: "snapchat", Title: "Snapchat", Group: "social",
		Domains: []string{"snapchat.com", "sc-cdn.net", "snap.com"}},
	{ID: "discord", Title: "Discord", Group: "social",
		Domains: []string{"discord.com", "discord.gg", "discordapp.com", "discord.media"}},
	{ID: "vk", Title: "VK", Group: "social",
		Domains: []string{"vk.com", "vk.me", "userapi.com", "vk-cdn.net"}},
}

func templateByID(id string) *ServiceTemplate {
	for i := range templateCatalog {
		if templateCatalog[i].ID == id {
			return &templateCatalog[i]
		}
	}
	return nil
}

// selectTemplates resolves ids to catalog entries; empty ids = whole catalog.
func selectTemplates(ids []string) []ServiceTemplate {
	if len(ids) == 0 {
		return templateCatalog
	}
	var out []ServiceTemplate
	for _, id := range ids {
		if t := templateByID(id); t != nil {
			out = append(out, *t)
		}
	}
	return out
}

// importedTemplates returns catalog entries whose param exists in the app.
// Catalog order → stable render → stable hash.
func importedTemplates(params map[string]Param) []ServiceTemplate {
	var out []ServiceTemplate
	for _, t := range templateCatalog {
		if _, ok := params[t.ID]; ok {
			out = append(out, t)
		}
	}
	return out
}

// templatesHash fingerprints the rendered import script. The router compares
// it against the last applied hash and re-imports only on change.
func templatesHash(templates []ServiceTemplate) string {
	if len(templates) == 0 {
		return ""
	}
	sum := sha256.Sum256([]byte(renderTemplatesRsc(templates)))
	return hex.EncodeToString(sum[:])[:12]
}

// renderTemplatesRsc generates an idempotent RouterOS 7 import script that
// creates, per service: an FQDN address-list and a forward drop rule with
// src-address-list=kids-devices — tagged hook:<id> and disabled=yes, so
// the regular remote-hook cycle takes over after import. It also migrates
// rules imported by older template versions: adds the missing kids scope
// and removes the LAN-wide dns/static NXDOMAIN entries.
func renderTemplatesRsc(templates []ServiceTemplate) string {
	var b strings.Builder
	b.WriteString(`# MikroTik Rule Toggle — service blocking templates (RouterOS 7)
# Generated by the hook server. Idempotent: safe to re-run, existing
# entries are kept. Everything is created disabled=yes — enable via the
# web panel (rules are tagged hook:<name>). Drop rules apply only to the
# kids-devices address-list (auto-synced from kid-control by remote-hook).
#
# Import:
#   /tool/fetch url="http://<server>:8080/mikrotik/templates.rsc" dst-path=templates.rsc
#   /import file-name=templates.rsc

# Drop rules go right before the established/related accept (if present)
:local est [/ip/firewall/filter find where chain=forward connection-state~"established"]
`)
	for _, t := range templates {
		list := "blocked-" + t.ID
		fmt.Fprintf(&b, "\n# --- %s (%s) ---\n", t.Title, t.Group)
		for _, d := range t.Domains {
			fmt.Fprintf(&b,
				":if ([:len [/ip/firewall/address-list find where list=\"%s\" && address=\"%s\"]] = 0) do={ /ip/firewall/address-list add list=%s address=%s comment=\"tpl:%s\" }\n",
				list, d, list, d, t.ID)
		}
		for _, r := range t.Ranges {
			fmt.Fprintf(&b,
				":if ([:len [/ip/firewall/address-list find where list=\"%s\" && address=\"%s\"]] = 0) do={ /ip/firewall/address-list add list=%s address=%s comment=\"tpl:%s static range\" }\n",
				list, r, list, r, t.ID)
		}
		// Migration from pre-kids-scope templates: LAN-wide NXDOMAIN out,
		// kids scope onto existing rules
		fmt.Fprintf(&b,
			":do { /ip/dns/static remove [find where comment=\"hook:%s\"] } on-error={}\n", t.ID)
		fmt.Fprintf(&b,
			":do { /ip/firewall/filter set [find where comment=\"hook:%s\" && !src-address-list] src-address-list=kids-devices } on-error={}\n", t.ID)
		fmt.Fprintf(&b, `:if ([:len [/ip/firewall/filter find where comment="hook:%s"]] = 0) do={
    :if ([:len $est] > 0) do={
        /ip/firewall/filter add chain=forward src-address-list=kids-devices dst-address-list=%s action=drop comment="hook:%s" disabled=yes place-before=($est->0)
    } else={
        /ip/firewall/filter add chain=forward src-address-list=kids-devices dst-address-list=%s action=drop comment="hook:%s" disabled=yes
    }
}
`, t.ID, list, t.ID, list, t.ID)
	}
	b.WriteString("\n:log info \"rule-toggle templates imported\"\n")
	return b.String()
}
